version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.24.1
    working_directory: /yaichi
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - run: |
          bin/test
